apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP     
  selector:
    app: backend      
  ports:
  - protocol: TCP
    port: 9966
    targetPort: 9966
---
apiVersion: v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend      
spec:
  replicas: 2
  containers:
  - name: backend
    image: callistoreg.azurecr.io/spring-petclinic-rest:latest
    ports:
    - containerPort: 9966
