apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend     
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend     
spec:
  replicas: 3
  containers:
  - name: frontend
    image: callistoreg.azurecr.io/spring-petclinic-angular:latest
    ports:
    - containerPort: 8080